### ISSUE TITLE
Options on Compression?

### ISSUE THREAD

**Issue by citibeth** [mateidavid/zstr#10]
Is there a way to set / control compression parameters when opening a stream?

[Nice library!  At first I tried boost, as per your suggestion.  But boost's filters are not completely general; they can only write to a "sink", not to a general ostream.  So that meant I couldn't write to a boost::interprocess::ovectorstream, which is what I really wanted to use as my sink.  Using zstr to write to a ovectorstream works like a charm!]

**Comment by ferdymercury** [comment]
See this fork: https://github.com/JGI-Bioinformatics/zstr/commit/96b1aaaf9d5d979214150f5e3e47645aaf416ccd for setting compression level

**Comment by ferdymercury** [comment]
Will be fixed by https://github.com/mateidavid/zstr/pull/9
