### ISSUE TITLE
the proper way of getting decompressed file size

### ISSUE THREAD

**Issue by passerbyd** [mateidavid/zstr#46]
A buffer is needed to hold the whole file after decompressing, how could I get the final file size?
It seems "seekg" and "tellg" could only get the original compressed size.

**Comment by ferdymercury** [comment]
Try this:
```
    // Get total number of uncompressed bytes
    uint64_t fileBytes = 0;
    {
        zstr::ifstream file(fileName, std::ios::binary);
        fileBytes = std::distance(std::istreambuf_iterator<char>(file), std::istreambuf_iterator<char>());
    }
```

**Comment by passerbyd** [comment]
> Try this:
> 
> ```
>     // Get total number of uncompressed bytes
>     uint64_t fileBytes = 0;
>     {
>         zstr::ifstream file(fileName, std::ios::binary);
>         fileBytes = std::distance(std::istreambuf_iterator<char>(file), std::istreambuf_iterator<char>());
>     }
> ```

Thanks @ferdymercury,  this indeed works.
but does std::distance read all bytes from the istream, and make it unusable?

**Comment by ferdymercury** [comment]
Yes, it reads all bytes and ends in the end of the stream. There is no other way to predict how many bytes are stored within, afaik, see https://stackoverflow.com/questions/9209138/uncompressed-file-size-using-zlibs-gzip-file-access-function.

The stream is not necessarily unusable, you could go back to the beginning of the file with seekg(). Or use an unnamed scope as above (or a separate function), and then open a new stream afterwards on the same file.

**Comment by jmakov** [comment]
seekg() is not working

**Comment by ferdymercury** [comment]
Hmm I am not sure why. Did you try seekoff instead?
Otherwise, the workaround would be to use an unnamed scope.
