### ISSUE TITLE
strerror problem on a Mac

### ISSUE THREAD

**Issue by mrzv** [mateidavid/zstr#5]
The various `ifdef`s at the beginning of `strict_fstream.hpp` that determine how to interact with `strerror_r` break for me on a Mac. Specifically, it drops into the third, GNU-specific case, but it should be using the second one. I quickly fixed my local copy by adding `defined(__APPLE__)` to the second case, but I'm not sure if it's the correct universal fix.

**Comment by erikor** [comment]
I encountered the same issue. As it seems possible some users might be using GCC rather than clang on their Macs, I used the following compiler directives, but I too am not sure how universal/portable this is:

```
#elif __APPLE__ && __clang__ && ! _GNU_SOURCE
// XSI-compliant strerror_r()
    if (strerror_r(errno, &buff[0], buff.size()) != 0)
    {
        buff = "Unknown error";
    }
#else 
// GNU-specific strerror_r()
    auto p = strerror_r(errno, &buff[0], buff.size());
    std::string tmp(p, std::strlen(p));
    std::swap(buff, tmp);
#endif
```

**Comment by lczech** [comment]
There are actually several [pull requests](https://github.com/mateidavid/zstr/pulls) for this exact issue already, but unfortunately, it seems that the repository is no longer maintained, as those have not been accepted in almost three years :-(

**Comment by ferdymercury** [comment]
@mateidavid are you still active in this repository? If not, could you add @lczech or myself as collaborators of the repository so that we can mantain it? Thanks in advance!

**Comment by ferdymercury** [comment]
If someone of you has Linkedin, maybe try to contact him through his profile: https://ca.linkedin.com/in/matei-david-aa12a4103

**Comment by erikor** [comment]
I have reached out to him via linked in invitation.

**Comment by sandsmark** [comment]
I completely forgot about upstream, but it seems like I've fixed more or less everything from the other PRs earlier, and I pulled in the last couple of things (that made sense) now, so this should be a superset of all open PRs (and more): https://github.com/mateidavid/zstr/pull/9

**Comment by ferdymercury** [comment]
Thanks @sandsmark! Did you also consider including the changes from https://github.com/JGI-Bioinformatics/zstr/commits/master ?
The CMakeLists seems useful.

**Comment by mateidavid** [comment]
Sorry guys, I've moved on to Java, kids, etc... I'll add @ferdymercury as collaborator.

**Comment by ferdymercury** [comment]
Thanks Matei! I don't have rights to add other contributors, could you assign me those?

Cheers

**Comment by mateidavid** [comment]
I don't know how...

**Comment by ferdymercury** [comment]
Oh, I see, then it might be because free accounts do not support this functionality. Can you add @sandsmark and @lczech as collaborators yourself? Thanks!!
