### ISSUE TITLE
can't compile in clang

### ISSUE THREAD

**Issue by hero2002** [mateidavid/zstr#50]
so I am trying to build for android and android ndk use clang
and I am getting this error
```
C:\enough_words_c_tcod\include\zstr/strict_fstream.hpp:77:12: error: cannot initialize a variable of type 'char *' with
      an rvalue of type 'int'
    char * p = strerror_r(errno, &buff[0], buff.size());
           ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by hero2002** [comment]
okay making it use the same code as the apple one fixed the issue

**Comment by hero2002** [comment]
@ferdymercury not sure why you assigned me :sweat_smile:

**Comment by ferdymercury** [comment]
ahh because you solved it yourself apparently ;)
