### ISSUE TITLE
Setting compression level in zstr::ofstream?

### ISSUE THREAD

**Issue by kiplingw** [mateidavid/zstr#63]
Hello everyone,

I've been looking through the `zstr.hpp` header and I can't seem to find out how to set the compression level in `zstr::ofstream`? 

I see zlib internally is tracking the compression level within the `zstr::ostreambuf`'s private `zstrm_p` parameter. The `zstr::ostreambuf` object is accessible from the `rdbuf()` of the `ofstream`, but the `zstrm_p` of course is not.

**Comment by ferdymercury** [comment]
Maybe via the `_level` constructor argument here? https://github.com/mateidavid/zstr/blob/master/src/zstr.hpp#L388

**Comment by kiplingw** [comment]
The problem is one typically opens an output stream via `zstr::ofstream` which doesn't appear to take that argument.

**Comment by ferdymercury** [comment]
Isn't https://github.com/mateidavid/zstr/blob/master/src/zstr.hpp#L462 what you are looking for?

**Comment by kiplingw** [comment]
Thanks @ferdymercury. It looks like it is, in fact, implemented in `zstr::ofstream`. I was confused because my distro ships version 1.1.1-5 of the package which doesn't have it. Do you know which upstream version was the first to allow setting the compression level in `zstr::ofstream`?

**Comment by ferdymercury** [comment]
It was done here https://github.com/mateidavid/zstr/pull/9

**Comment by ferdymercury** [comment]
I d suggest just cloning the git repo, it's header only. V1.0.4 should work but check current master better

**Comment by kiplingw** [comment]
Strange because I am [using](https://packages.ubuntu.com/jammy/libhpptools-dev) version 1.1.1 and it doesn't support it in `zstr::ofstream`'s constructor?

**Comment by kiplingw** [comment]
Ah yes, good point. I don't think zstr is packaged on its own.
