### ISSUE TITLE
GZIP compression support?

### ISSUE THREAD

**Issue by irskid5** [mateidavid/zstr#64]
Hey guys,

I was wondering if it is possible to add GZIP compression functionality? The original zlib.h library contains code for GZIP compression, yet the wrapper does not.

Thanks!

**Comment by ferdymercury** [comment]
There is no active developer here but PR are welcome ;)

**Comment by lczech** [comment]
Hey @irskid5,

the library already defaults to writing gzip, no need to do anything extra. The `deflateInit2` function of the underlying zlib uses gzip depending on `window_bits`, see [here](https://stackoverflow.com/q/72499500) and [here](https://zlib.net/manual.html#Advanced). And this library here defaults to a value that corresponds to gzip, see [here](https://github.com/mateidavid/zstr/blob/755da7890ea22478a702e3139092e6c964fab1f5/src/zstr.hpp#L269) and [here](https://github.com/mateidavid/zstr/blob/755da7890ea22478a702e3139092e6c964fab1f5/src/zstr.hpp#L107).

Does that make sense?

Cheers
Lucas

**Comment by irskid5** [comment]
Beautiful! Thank you very much!

**Comment by irskid5** [comment]
Beautiful! Thanks alot!
